/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public MyCaharaters/my-character.glb 
*/

import React, { useEffect, useRef } from "react";
import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useControls } from "leva";

export function MyCharacter(props) {
  const { animation }=props
  const group = useRef();
  const { headFollow }= useControls({headFollow:false})
  const { nodes, materials } = useGLTF("/models/my-character.glb");

  const { animations: danceAnimation } = useFBX("/animations/SillyDancing.fbx");
  const { animations: jumpAnimation } = useFBX("/animations/Jump.fbx");
  const { animations: hiphopAnimation } = useFBX("/animations/HipHopDancing.fbx");
  const { animations: JogInCircleAnimation } = useFBX("/animations/JogInCircle.fbx");
  const { animations: bDance1Animation } = useFBX("/animations/BreakdanceFootwork1.fbx");
  const { animations: bDance2Animation } = useFBX("/animations/BreakdanceFreezeVar2.fbx");
  const { animations: bDance3Animation } = useFBX("/animations/BreakdanceFreezeVar3.fbx");

  danceAnimation[0].name = "dance";
  jumpAnimation[0].name = "jump";
  hiphopAnimation[0].name = "hiphop";
  JogInCircleAnimation[0].name="jog"
  bDance1Animation[0].name="bd1"
  bDance2Animation[0].name="bd2"
  bDance3Animation[0].name="bd3"


  const { actions } = useAnimations([danceAnimation[0],jumpAnimation[0],hiphopAnimation[0],JogInCircleAnimation[0],bDance1Animation[0],bDance2Animation[0],bDance3Animation[0]], group);

  console.log({actions})

  useFrame((state) => {
    if(headFollow){
      console.log({ element:group.current,headFollow })
      group.current.getObjectByName("Head")?.lookAt(state.camera.position);
    }

  });

  useEffect(() => {
    if(animation){
      actions[animation].reset().play();
    }

    return ()=>{
      actions[animation].reset().stop();
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation-x={-Math.PI / 2}>
        <group name="Scene">
          <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <primitive object={nodes.mixamorigHips} />
            <skinnedMesh
              name="Ch03"
              geometry={nodes.Ch03.geometry}
              material={materials.Ch03_Body}
              skeleton={nodes.Ch03.skeleton}
            />
          </group>
          <group name="Armature001" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <primitive object={nodes.mixamorigHips_1} />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models//my-character.glb");
